site_name: Python Tutorials

theme:
  name: material
  language: en
  features:
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - toc.follow
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ashishbindra2
    - icon: fontawesome/brands/linkedin
      link: https://in.linkedin.com/in/ashishbindra2/

markdown_extensions:
  - sane_lists
  - md_in_html
  - admonition
  - footnotes
  - attr_list
  - toc:
      permalink: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


plugins:
  - search
  - awesome-pages

nav:
  - Home: index.md
  - Assignments:
      - Overview: assignments/index.md
      - Assignment: assignments/Assignment.md
      - Assignment 1: assignments/assignment1.md
  - Interview Questions:
      - Overview: interview-questions/index.md
      - Interview Theory: interview-questions/interview-theory.md
      - Interview Practical: interview-questions/interview-pratical.md
      - Coding Questions: interview-questions/coding.md
      - infosis: interview-questions/infosis-interview.md
      - MCQ 1: interview-questions/Python_MCQ.md
      - Important : interview-questions/important.md
      - String : interview-questions/string.md
  - Python Tutorials:
      - Overview :  python_tutorials/Basic.md
      - identifers: python_tutorials/identifers.md
      - data types: python_tutorials/Data_types.md
      - String: python_tutorials/string.md   
      - fstring: python_tutorials/fstring.md     
      - List :  python_tutorials/List.md
      - Dict :  python_tutorials/Dict.md
      - Set :  python_tutorials/Set.md
      - os :  python_tutorials/os.md
      - File :  python_tutorials/File.md
      - time :  python_tutorials/time.md
      - Random :  python_tutorials/Random.md
      - re :  python_tutorials/RE.md
      - secrete :  python_tutorials/secrete.md
      - decorator :  python_tutorials/decorator.md
      - Exception: python_tutorials/Exception.md
      - oops: python_tutorials/oops.md
      - logging: python_tutorials/logging.md
      - Serialization: python_tutorials/Serialization.md
      - unittesting: python_tutorials/unittesting.md
  - Python Versions:
      - python 3.8 : python-versions/python_3.8.md
      - python 3.9 : python-versions/python-3.9.md
      - python 3.10 : python-versions/python-3.10.md
      - python 3.11 : python-versions/python-3.11.md
      - Python 3.12: python-versions/python-3.12.md
      - Python 3.13: python-versions/python-3.13.md
  - UV: uv.md
  - Tools: 
    - facker: tool/Facker.md
    - pytest: tool/pytest.md

copyright: |
  &copy; 2024 <a href="https://github.com/ashishbindra2" target="_blank" rel="noopener">Ashish Bindra</a>
 